### ISSUE TITLE
Testing illegal Unicode hosing things

### ISSUE THREAD

**Issue by cweb** [w3c/testharness.js#126]
I've been testing URLs and noticed that my tests containing illegal Unicode are hosing things, not sure where in the pipeline but it seems to be inside the assert_equals().  I've narrowed down the problem test case to this:  http://testcases.org/test/unicode/buith.html

The second test case seems to be the problem, testing an illegal half-surrogate U+D800. 

```javascript
assert_equals(uni, uni2, "U+D800");
```

where:

```javascript
var uni = '\uD800\u597d';
var uni2 = '\uFFFD\u597d';
```

Oddly, the test of 'uni' against itself doesn't hose things:

```javascript
assert_equals(uni, uni, "U+D800");
```

**Comment by Ms2ger** [comment]
The issue is with any failing assertion, actually, and is caused by the location of your `testharness.js` copy: under `js` rather than `resources`. This causes us to iloop here:
```js
        var re = /\/resources\/testharness\.js/;
        var i = 0;
        // Fire remove any preamble that doesn't match the regexp
        while (!re.test(lines[i])) {
            i++
        }
```

**Comment by cweb** [comment]
Ah perfect, moving testharness.js to /resources solved it, thanks.
