### ISSUE TITLE
Test that passing null to a non-nullable type throws TypeError

### ISSUE THREAD

**Issue by foolip** [w3c/testharness.js#151]
As discussed on IRC:
http://krijnhoetmer.nl/irc-logs/whatwg/20150929#l-177

It would be nice to test with non-null inputs of the wrong type too, but that seems hard to do in the general case.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7161; please continue all discussion there.
