### ISSUE TITLE
Support DOMTokenList

### ISSUE THREAD

**Issue by gsnedders** [w3c/testharness.js#153]
We want a number of tests to get auto generated for DOMTokenList, along the lines of how length and item correspond, etc.

**Comment by jgraham** [comment]
Huh? This doesn't sound like something that would go in testharness.js

**Comment by jgraham** [comment]
I guess you possibly mean for idlharness.js…

**Comment by gsnedders** [comment]
Yes, for idlharness.js, sorry for not specifying that.

**Comment by gsnedders** [comment]
Looking closely at this I'm less sure we want this. Bleh.
