### ISSUE TITLE
DOM hierarchy error with XHTML and SVG

### ISSUE THREAD

**Issue by DLehenbauer** [w3c/testharness.js#157]
testharnessreport.js attempts to append a script element containing the JSON serialized test results to the last node of the document.  Depending on what the last node happens to be, this can result in a nonconforming document.  Strict document types like XHTML and SVG will throw a DOM hierarchy request error as a result.

The Edge team is testing a fix in our fork that seems to work for our XHTML and SVG tests, and will contribute it back shortly.

(Thanks to @KurtCattiSchmidt for noticing and diagnosing the issue.)

**Comment by gsnedders** [comment]
What browser is throwing a hierarchy error (`HierarchyRequestError` I presume)? Edge? I can't see anything in [DOM](https://dom.spec.whatwg.org) or [DOM Level 3 Core](http://www.w3.org/TR/DOM-Level-3-Core/core.html) that justifies throwing in those cases?

**Comment by DLehenbauer** [comment]
Ch/FF/Edge seem to agree it's a `HierarchyRequestError` to append a script element to a text node in an XHTML document.  The error is easy to miss because it goes silently to the console after TestHarness.js has already displayed the test results.

Here's a short repro:

    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
      <script src="../resources/testharness.js" type="text/javascript"></script>
      <script src="../resources/testharnessreport.js" type="text/javascript"></script>
    </head>
    <body>
      <script type="text/javascript">
        test(function () {}, "See HierarchyRequestError in console.");
      </script>
    </body>
    </html>

**Comment by gsnedders** [comment]
Oh. Duh. I failed to read the original code correctly! Yes, I agree the current behaviour is bogus.

The comment "To avoid hierachy errors with strict doc types, prefer appending to the body" is bogus, though: `document.documentElement.appendChild(results_element)` should work everywhere (regardless of DOCTYPE). What causes the hierarchy error is appending to a Text node, which can't have children.  I do wonder if it would be simpler to just have it always in the same place (i.e., removing the `document.body` special case); thoughts on that @jgraham?

**Comment by jgraham** [comment]
I think the document.body special case is good.

I'm also slightly surprised that someone is using the default testharnessreport.js in production; that's really only designed for authoring tests and will do a bunch of things that slow down your test run. For comparison, the production version that we use for gecko testruns is https://github.com/w3c/wptrunner/blob/master/wptrunner/testharnessreport.js i.e. it just sets up testharness.js in a way that makes it compatible with wptrunner.

**Comment by DLehenbauer** [comment]
@gsnedders, appending the `<script>` to the end of the XHTML document seems to be permitted by the browsers I tested, but the resulting document fails W3C's validator:

    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
      <title></title>
    </head>
    <body>
    </body>
    <script type="text/javascript">
      // Line 8, Column 31: document type does not allow element "script" here
    </script>
    </html>

(@jgraham, thank you for the tip on optimizing testharnessreport.js for production.)

**Comment by cvrebert** [comment]
I believe #160 fixed this.
