### ISSUE TITLE
Add assert_throws_exactly/promise_rejects_exactly

### ISSUE THREAD

**Issue by domenic** [w3c/testharness.js#165]
In streams tests, there is a lot of tests that a given error is caught and turned into an appropriate promise rejection, or that an error is re-thrown from the appropriate place. For these, it would be very helpful to have a version of assert_throws/promise_rejects that tests not against the .name property, but against the exact object identity of the thrown error.

Would a pull request adding this function be accepted?

**Comment by Ms2ger** [comment]
There's some tests that use
```js
  var test_error = { name: "test" };
```
for that purpose. Not entirely satisfying, though.

@jgraham wdyt?

**Comment by domenic** [comment]
One benefit I just noticed is that it would allow you to test that non-objects are rethrown/propagated, e.g. `undefined` or `5`.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7165; please continue all discussion there.
