### ISSUE TITLE
DedicatedWorkerGlobalScope type is named with WorkerGlobalScope in the Edge

### ISSUE THREAD

**Issue by cpsgchue** [w3c/testharness.js#173]
Testharness.js support 3 web worker types when creating test environment (in the create_test_environment); Dedicated/Shared/ServerceWorkerGlobalScope.   Microsoft Edge support only DedicatedWorkerGlobalScope worker type , but with name of ‘WorkerGlobalScope’.   This different type name make create_test_enviroment throw exception when testharness.js is imported from the web worker scripts.

The proposal is to add extra check after ‘ServiceWorkerGlobalScope’ in the create_test_environment.

if ('WorkerGlobalScope' in self &&
   self instanceof WorkerGlobalScope) {
   return new DedicatedWorkerTestEnvironment();
}

**Comment by Ms2ger** [comment]
This seems like a bug in Edge that should be fixed. I guess I'd probably take a PR, though.
