### ISSUE TITLE
A more informative message when array_equals fails would be nice

### ISSUE THREAD

**Issue by bzbarsky** [w3c/testharness.js#176]
It's particularly bad in the wrong length case (is one item missing?  Which one?  Are they all just bogus?) but even in the right length case it's not obvious from the error whether things are reordered but generally all there or just totally bogus.  Showing the actual array contents might be helpful.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7168; please continue all discussion there.
