### ISSUE TITLE
'assert_readonly' implementation is problematic

### ISSUE THREAD

**Issue by DLehenbauer** [w3c/testharness.js#177]
@AlexeyKor recently noticed unexpected results from 'assert_readonly()' and dug into why.  He found that the current implementation tests for readonly by attempting to set the current value and inspecting the property afterward to see if the value changed:

``` javascript
function assert_readonly(object, property_name, description)
{
    var initial_value = object[property_name];
    try {
        //Note that this can have side effects in the case where
        //the property has PutForwards
        object[property_name] = initial_value + "a"; //XXX use some other value here?
        assert(same_value(object[property_name], initial_value),
                   "assert_readonly", description,
                   "changing property ${p} succeeded",
                   {p:property_name});
    } finally {
        object[property_name] = initial_value;
    }
}
```

This is problematic, as `initial_value + 'a'` is not guaranteed to be valid value for the property, in which case the set attempt might throw, or be silently ignored even if the property is writable.  (This is particularly true if the property doesn't accept strings.)

I'm guessing this code predates ES5, and now should be updated to inspect the property's descriptor.  We can potentially go a step further, and ensure that attempting to set the property in a 'use strict' block throws the proper error.

If this seems uncontroversial, @AlexeyKor or I are happy to implement.

**Comment by Ms2ger** [comment]
I'm not sure how useful that function is anyway. Do you know if it's widely used?

**Comment by jgraham** [comment]
I think it is used, and I'm happy to see a better implementation (this was originally written when ES3.1 was the latest thing).

**Comment by zqzhang** [comment]
Yes, a better implementation is appreciated.

**Comment by gsnedders** [comment]
I remember some discussion a while ago (perhaps from me immediately after testharness.js was written?) about this, and @jgraham voicing concerns as to the accuracy of property descriptors for host objects (or rather whatever they're called in ES2015 now :)), which really was justified in the days before WebIDL implementations became widespread. Perhaps we can change this now, though I certainly feel like we should have *some* tests somewhere that host objects behave correctly wrt property descriptors.

**Comment by gsnedders** [comment]
For comparison, see [opjsunit's assertReadOnly](https://github.com/operasoftware/presto-testo/blob/master/core/standards/scripts/opjsunit/harness/opjsunit.js#L253) which was likely originally related.

**Comment by DLehenbauer** [comment]
Thanks.  The opjsunit implementation looks fundamentally like the right thing to do.  The only thing I intentionally omitted was the comparison with the initial value since, *technically*, the value of a readonly property can still change (e.g., a get accessor that returns Date.now().)

**Comment by gsnedders** [comment]
Looking at this again, I'm wondering what this is actually meant to be testing: are we testing `ReadOnly` in the ES3 sense, or `readonly` in the WebIDL sense, given that would alter the expected behaviour? From memory I want to say it's meant to be the former?

**Comment by gsnedders** [comment]
A brief look makes it look like it's only really used in the WebIDL sense, regardless of the original intention (which I want to say was the ES3 sense, but this was obviously many years ago!). I'd push for moving current usage over to `idlharness.js` (which does a far better test of property descriptors), and drop `assert_readonly`, I think. @jgraham, thoughts?

**Comment by gsnedders** [comment]
@Ms2ger: usage is

```
./ambient-light/DeviceLightEvent_tests.js:    assert_readonly(event, 'value', 'readonly attribute value');
./dom/traversal/NodeIterator.html:    assert_readonly(iter, 'root');
./dom/traversal/NodeIterator.html:    assert_readonly(iter, 'whatToShow');
./dom/traversal/NodeIterator.html:    assert_readonly(iter, 'filter');
./dom/traversal/NodeIterator.html:    assert_readonly(iter, 'referenceNode');
./dom/traversal/NodeIterator.html:    assert_readonly(iter, 'pointerBeforeReferenceNode');
./dom/traversal/TreeWalker-basic.html:    assert_readonly(walker, 'root');
./dom/traversal/TreeWalker-basic.html:    assert_readonly(walker, 'whatToShow');
./dom/traversal/TreeWalker-basic.html:    assert_readonly(walker, 'filter');
./html/semantics/scripting-1/the-template-element/template-element/content-attribute.html:    assert_readonly(template, 'content',
./html/semantics/scripting-1/the-template-element/template-element/content-attribute.html:    assert_readonly(template, 'content',
./html/semantics/scripting-1/the-template-element/template-element/content-attribute.html:    assert_readonly(template, 'content',
./html/semantics/scripting-1/the-template-element/template-element/content-attribute.html:    assert_readonly(template, 'content',
./html/semantics/scripting-1/the-template-element/template-element/content-attribute.html:    assert_readonly(template, 'content',
./html/semantics/scripting-1/the-template-element/template-element/content-attribute.html:    assert_readonly(template, 'content',
./html/semantics/scripting-1/the-template-element/template-element/content-attribute.html:    assert_readonly(template, 'content',
./IndexedDB/idbcursor-direction.htm:                assert_readonly(cursor, 'direction');
./IndexedDB/idbcursor-direction.htm:                assert_readonly(cursor, 'direction');
./IndexedDB/idbcursor-key.htm:                assert_readonly(cursor, 'key');
./IndexedDB/idbcursor-primarykey.htm:                assert_readonly(cursor, 'primaryKey');
./IndexedDB/idbcursor-source.htm:            assert_readonly(cursor, 'source');
./pointerevents/pointerevent_support.js:                assert_readonly(event.type, name, event.type + "." + name + " cannot be changed");
./proximity/DeviceProximityEvent_tests.js:        assert_readonly(event, 'value', 'readonly attribute value');
./proximity/DeviceProximityEvent_tests.js:        assert_readonly(event, 'min', 'readonly attribute min');
./proximity/DeviceProximityEvent_tests.js:        assert_readonly(event, 'max', 'readonly attribute max');
./proximity/UserProximityEvent_tests.js:        assert_readonly(event, 'near', 'readonly attribute near');
```

So only 11 files in all of w-p-t…

**Comment by Ms2ger** [comment]
I would be happy to remove it, but will leave the decision to @jgraham. We should probably also check CSS tests.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7169; please continue all discussion there.
