### ISSUE TITLE
idlharness.js checks that attribute getters on a global do not require an explicit 'this'

### ISSUE THREAD

**Issue by cdumez** [w3c/testharness.js#182]
idlharness.js checks that attribute getters on a global do not require an explicit 'this'. The relevant code is:

```
            if (gotValue) {
                assert_equals(propVal, getter.call(undefined),
                              "Gets on a global should not require an explicit this");
            }
```

under IdlInterface.prototype.test_member_attribute

While Firefox seems to behave this way, the latest Web IDL specification does not seem to have any mention of this (unless I missed something).

Relevant specification:
- [Attribute getters](http://heycam.github.io/webidl/#dfn-attribute-getter)
  Says to use 'this' value and does not mention anything about using something else when there is no explicit this.

Unlike for [operations](http://heycam.github.io/webidl/#es-operations), where the spec does say:

> Otherwise, if the interface on which the operation appears has an [[ImplicitThis]](http://heycam.github.io/webidl/#ImplicitThis) extended attribute, and the this value is null or undefined, then O is the ECMAScript global object associated with the Function object.

The specification for  [[ImplicitThis]](http://heycam.github.io/webidl/#ImplicitThis) clearly states that it applies to operations but NOT attribute getters, and that throwing is the right thing to do for attribute getters.

**Comment by cdumez** [comment]
@heycam Did I understand the Web IDL specification correctly?

**Comment by bzbarsky** [comment]
The IDL spec here got update in https://github.com/heycam/webidl/pull/217 that makes it clear that attributes on the global do in fact use the global as `this` if `undefined` or `null` are passed.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7170; please continue all discussion there.
