### ISSUE TITLE
Support callbacks

### ISSUE THREAD

**Issue by lanthaler** [w3c/testharness.js#20]
The tests for the [JSON-LD 1.0 Processing Algorithms and API](http://json-ld.org/spec/latest/json-ld-api/) fail because callbacks are not supported yet. The idlharness test can be found here:

http://json-ld.org/test-suite/idltest/

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7147; please continue all discussion there.
