### ISSUE TITLE
Support Node.js tests

### ISSUE THREAD

**Issue by ibelem** [w3c/testharness.js#200]
Hi @jgraham, @Ms2ger do you have any plan to support testharness.js run in Node.js environment rather than run in browser/web runtime only? The background is we need to run idlharness.js to automatically generates tests for WebIDL interfaces in Node.js environment.

Seems like https://www.npmjs.com/package/webidl2 is using mocha and expect.js to do this work.

https://www.npmjs.com/package/mocha
https://www.npmjs.com/package/expect.js

**Comment by Ms2ger** [comment]
I'm not sure what that would involve exactly. If we can do it without too much maintenance for us, I imagine we'd be willing to accept a PR.

**Comment by domenic** [comment]
I have hacked up https://github.com/domenic/wpt-runner for this purpose. Right now it only has one consumer ([whatwg/streams](https://github.com/whatwg/streams/tree/master/reference-implementation)) so it might not work super great, but you might find it useful.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7174; please continue all discussion there.
