### ISSUE TITLE
'assert_type_is' always throw for Promise<SomeInterface> of attribute

### ISSUE THREAD

**Issue by schien** [w3c/testharness.js#212]
Given an IDL like

```
interface Foo {
  attribute Promise<Bar> attr;
};
```

`assert_type_is` will throw `Unrecognized type [object Object]` from [https://github.com/w3c/testharness.js/blob/master/idlharness.js#L554].

This is because in [https://github.com/w3c/testharness.js/blob/master/idlharness.js#L450] expect the `type.idlType` is a string for primitive types. However, the idlType is an object represents `Bar` type, something like:

```
{
  "sequence":false,
  "generic":"Promise",
  "nullable":false,
  "array":false,
  "union":false,
  "idlType": {
    "sequence":false,
    "generic":null,
    "nullable":false,
    "array":false,
    "union":false,
    "idlType":"Bar"
  }
}
```

There are two test cases I know that affected by this issue:
[https://github.com/w3c/web-platform-tests/blob/master/presentation-api/receiving-ua/idlharness.html#L97]
[https://github.com/w3c/web-platform-tests/blob/master/webrtc/rtcpeerconnection/rtcpeerconnection-idl.html#L88]

**Comment by tidoust** [comment]
Bug fixed by PR #213, which just landed.
