### ISSUE TITLE
Disable the timeout automatically for manual tests?

### ISSUE THREAD

**Issue by tidoust** [w3c/testharness.js#217]
Tests that check features that require some initial user gesture are typically semi-manual: they require the user to do something, e.g. click on a button, and the test can then use the test harness to compute and report the result to the test runner automatically.

It's hard to predict how long the user is going to need to read and follow the instructions, and these tests disable the harness timeout with a call to `setup({explicit_timeout: true});`.

It's easy to forget that this call is needed though. How about disabling the timeout automatically for tests that end with `-manual.html`? Or are there manual tests that need the timeout?

I'd be happy to prepare a pull request if that sounds like a good idea (and an update to the documentation to mention that case).

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7176; please continue all discussion there.
