### ISSUE TITLE
Attempt to dump offending objects in assert_array_equals and assert_object_equals

### ISSUE THREAD

**Issue by pwnall** [w3c/testharness.js#227]
Both `assert_array_equals` and `assert_object_equals` check their arguments piece by piece (element by element / property by property). This approach is sufficient when the assertions pass, but has a side-effect that when the assertions fail, we get sub-optimal debugging information.

Please consider building the assertion failure messages for these two functions in a more deliberate way. For example, when comparing two arrays, I'd like to see their elements in a JSON-like output (bonus points for GitHub-like diff highlighting).

Solving this issue would make it easier to use WPT to understand the differences in browser behaviors, and to debug & fix interoperability issues. Thank you very much!

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7179; please continue all discussion there.
