### ISSUE TITLE
Finish updating idlharness to Promise-returning attribute behavior

### ISSUE THREAD

**Issue by bzbarsky** [w3c/testharness.js#233]
These now reject instead of throwing.

I fixed the common cases (where the harness tests intended exceptions) in https://github.com/w3c/testharness.js/pull/232 but the cases where the attr getter actually happens to throw when you just call it on a reasonable object still need fixing.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7180; please continue all discussion there.
