### ISSUE TITLE
Asynchronous step function that does not modify this value

### ISSUE THREAD

**Issue by JosephPecoraro** [w3c/testharness.js#236]
When attempting to write an async test, `t.step_func` is useful for wrapping a callback function, however it modifies the `this` value within the callback. I'd like to add a variant that doesn't modify the this value, `t.step_func_unmodified_this`.

---

### Implementation (simplified)

```js
Test.prototype.step_func_unmodified_this = function(func)
{
    var t = this;
    return function() {
        return t.step.apply(test_this, [func, this].concat(Array.from(arguments));
    };
}
```

### Docs

For asynchronous callbacks where the `this` value is significant, `step_func_unmodified_this` can be used. For example:

```js
var observer = new Observer(t.step_func_unmodified_this(function() {
    assert_true(this instanceof Observer, "this value must be Observer");
    t.done();
}));
```

---

Currently the above test would need to be written something like:

```js
var finish = t.step_func(function() { t.done(); });
var observer = new Observer(function() {
    var self = this;
    t.step(function() {
        assert_true(self instanceof Observer, "this value must be Observer");
        finish();
    });
});
```

Which is quite obtuse, and requires using a different name for `this` even though `this` is what is being tested.

**Comment by gsnedders** [comment]
What does `step_func` have as `this` when it does call?

**Comment by JosephPecoraro** [comment]
The `this` value is test object created by `async_test`:

```js
let x = async_test(function(t) {
    setTimeout(t.step_func(function() {
        console.log(this === x); // true
        console.log(this === t); // true
        t.done();
    }));
}, "Title");

**Comment by JosephPecoraro** [comment]
You could change `Test.prototype.step_func` to not modify the `this` value if an explicit `this_obj` was not provided.

Something like: (untested)

```js
Test.prototype.step_func = function(func, this_obj)
{
    var test_this = this;
    var has_explicit_this_obj = arguments.length > 1;

    return function()
    {
        var func_this = has_explicit_this_obj ? this_obj : this;
        return test_this.step.apply(test_this, [func, func_this].concat(
            Array.prototype.slice.call(arguments)));
    };
};
```

I wasn't sure if anything relied on this behavior (I only just started using testharness.js today).

**Comment by gsnedders** [comment]
> I wasn't sure if anything relied on this behavior (I only just started using testharness.js today).

I have no idea! I'm wondering if we can get away with that. :)

**Comment by JosephPecoraro** [comment]
Do you have a way of running all (or a large portion of) the tests? I'm afraid if I do it I won't be able to test enough of the tests to guarantee there will be no regressions.

**Comment by gsnedders** [comment]
I can, though it takes a while. Probably easier when I'm not travelling and using my laptop. :)

**Comment by Ms2ger** [comment]
I'm a little concerned about changing this; would using `.bind(this)` be sufficient?

**Comment by JosephPecoraro** [comment]
`bind` would override the `this` that we are trying to test. Or were you thinking of using it on something else?

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7182; please continue all discussion there.
