### ISSUE TITLE
Look through TTWF tutorial and see if it has useful content

### ISSUE THREAD

**Issue by gsnedders** [w3c/testharness.js#244]
This is https://github.com/w3c/testtwf-website-src/blob/f29957b16f1df126d0ee62cf133f4ef67d888c0e/docs/testharness-tutorial.md

It's currently not linked to from anywhere on the TTWF website or elsewhere in the documentation; we should merge this into our own website. It will soon be gone with a redirect to the API documentation which it mostly duplicates.

This is also https://github.com/w3c/testtwf-website/issues/123

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7183; please continue all discussion there.
