### ISSUE TITLE
[idlharness] address changes in interface object bindings

### ISSUE THREAD

**Issue by tobie** [w3c/testharness.js#246]
PR:  heycam/webidl#313

In particular:

* Clarify that legacy callback interfaces are function objects.
* Give them a length property.
* Require new for Named Constructors.
* Disallow using [NoInterfaceObject] on callback interfaces with constants.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7184; please continue all discussion there.
