### ISSUE TITLE
Remove ServiceWorker+MessagePort UA detection

### ISSUE THREAD

**Issue by sfuqua** [w3c/testharness.js#247]
#239 introduces some changes to service worker testability. As part of that change, a UA sniff for Microsoft Edge is introduced due to the browser currently not supporting MessagePort in a ServiceWorker context - this is difficult to feature detect properly since the feature check needs to run in the worker context, not the client page's context.

This issue tracks removing the UA check either completely (once it is no longer needed) or with some sort of channel between the worker and the client page to communicate feature status.

The relevant code is at the top of the `create_remote_worker` function introduced in the referenced PR.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7185; please continue all discussion there.
