### ISSUE TITLE
Support the "SecureContext" extended flag

### ISSUE THREAD

**Issue by tidoust** [w3c/testharness.js#249]
The [`SecureContext`](https://heycam.github.io/webidl/#SecureContext) extended flag in WebIDL is interesting in that the result depends on the context the test runs in.

If IDL tests are run in a not secure context, the IDL harness should make sure that IDL definitions marked with a `SecureContext` flag are not exposed.

**Comment by tobie** [comment]
Ideally, you want to get wpt-runner to run such tests on both protocols.

@jgraham, @gsnedders: any idea how to go about that?

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7186; please continue all discussion there.
