### ISSUE TITLE
Implement checking for class-side inheritance

### ISSUE THREAD

**Issue by Ms2ger** [w3c/testharness.js#26]
See http://lists.w3.org/Archives/Public/public-script-coord/2013AprJun/0031.html. If the spec is changed to follow this, we should fix idlharness.js to follow suit.

**Comment by gsnedders** [comment]
Has the spec actually changed? It appears Gecko's behaviour has changed, but I'm not sure what's actually being talked about here. Digging into ES6 I'm still not sure what the hell is going on here.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7150; please continue all discussion there.
