### ISSUE TITLE
Do not output default error messages when custom message is given.

### ISSUE THREAD

**Issue by duerst** [w3c/testharness.js#37]
Working on encoding tests, I discovered that testharness.js outputs both the default error message and the custom message when the later is given as an argument. It looks like this:
Fail    HTML/Web Encoding 'windows-874' of byte value: DB   assert_equals: expected "U+FFFD" but got "" (U+F8C1) expected "�" but got ""
The first part (up to "(U+F8C1)") is the custom message, where I have added the character number. I don't need the second part anymore, but I don't know how to get rid of it. Tobie said "Yes, we need to fix the library. ;-)" and asked me to post this issue here.
/cc @tobie

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7151; please continue all discussion there.
