### ISSUE TITLE
Throw "Uncaught RangeError: Invalid array length" in testharness.js

### ISSUE THREAD

**Issue by jshentux** [w3c/testharness.js#54]
Calling a undefined object's property in setup() function will throw this exception.
For example:
setup(function(){a.b;});

**Comment by gsnedders** [comment]
So that setup function throws a RangeError?

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7152; please continue all discussion there.
