### ISSUE TITLE
Support [EnsureUTF16]

### ISSUE THREAD

**Issue by Ms2ger** [w3c/testharness.js#56]

**Comment by gsnedders** [comment]
`[EnsureUTF16]` seems to be dropped from the WebIDL spec.

**Comment by inexorabletash** [comment]
Yep, replaced with the __USVString__ type, which is supported. See also #92 if you're following a trail of breadcrumbs.

**Comment by gsnedders** [comment]
Yeah, that was eventual conclusion. #155 fixes #92, FWIW.
