### ISSUE TITLE
Feature request - simpler TypeError testing

### ISSUE THREAD

**Issue by sof** [w3c/testharness.js#62]
The common way to test for TypeError currently appears to be

  assert_throws(new TypeError(), fun);  // or, minimally, {name: "TypeError"}.

Testing for TypeError isn't uncommon when writing API coverage tests, wanting to check if the type conversion & input value is handled as required by WebIDL and underlying spec. So, how about providing a simpler way to assert for TypeError (and other native errors, possibly)? The above form isn't as succinct as it could be, I'd argue.

If this has already been considered and decided against, my apologies.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7153; please continue all discussion there.
