### ISSUE TITLE
Unhelpful failure reporting

### ISSUE THREAD

**Issue by darobin** [w3c/testharness.js#75]
In http://www.w3c-test.org/html/browsers/the-window-object/window-properties.html the first failure I get with Firefox, for test "EventTarget method: addEventListener", is:

```
assert_equals: expected function "function addEventListener() { [native code] }" but got function "function addEventListener() { [native code] }"
```

**Comment by gsnedders** [comment]
I don't see how we can do better than the current; that test should probably define an error message.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7154; please continue all discussion there.
