### ISSUE TITLE
How to handle mock or automated behavior?

### ISSUE THREAD

**Issue by scheib** [w3c/testharness.js#85]
Some tests require the platform or user to be mock-ed or automated for tests to run on automated infrastructure. For example, Chromium LayoutTests have access to [TestRunner](https://code.google.com/p/chromium/codesearch#search/&sq=package:chromium&type=cs&q=file:/test_runner/test_runner.h) which exposes methods such as [window.testRunner.setMockScreenOrientation](https://code.google.com/p/chromium/codesearch#search/&sq=package:chromium&type=cs&q=\"setMockScreenOrientation\").

However, without care these tests will not function when used in other browsers, or with manual testing. One example are the Chromium Pointer Lock tests using [doNextStepWithUserGesture](https://code.google.com/p/chromium/codesearch#search/&sq=package:chromium&type=cs&q=doNextStepWithUserGesture) which allow automation to mock a user-gesture (e.g. mouse click/key press) but also provide a way for manual testers to progress tests.

Has design been discussed to extend testharness with a mock concept that browsers can populate and which when possible falls through to manual instructions?

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7156; please continue all discussion there.
