### ISSUE TITLE
sequential_async_test

### ISSUE THREAD

**Issue by mvano** [w3c/testharness.js#96]
I'd like to run multiple async tests from a single page, but execute them sequentially, not in parallel. The idea would be for later tests to delay execution until the previous ones are done.

The goal would be to make tests that share state (across the tests, or in the object under test) be deterministic. Here's a contrived example:

``` javascript
var i = 0;

sequential_async_test(function(test) {
    setTimeout(function() {
        assert_equals(i, 0);
        i++;
        test.done();
    }, Math.round(Math.random() * 100));
}, 'Async test 0');

sequential_async_test(function(test) {
    setTimeout(function() {
        assert_equals(i, 1);
        i++;
        test.done();
    }, Math.round(Math.random() * 100));
}, 'Async test 1');
```

I guess the alternative is to make separate pages, each with a single `async_test`. I'll probably do that for the time being.

**Comment by jgraham** [comment]
You can use add_result_callback to achieve this.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7157; please continue all discussion there.
